export const POLISH_CITIES = [
  "Bielany Wrocławskie",
  "Bielawa",
  "Bierutów",
  "Bogatynia",
  "Boguszów-Gorce",
  "Bolesławiec",
  "Bolków",
  "Brzeg Dolny",
  "Bystrzyca Kłodzka",
  "Chocianów",
  "Chojnów",
  "Dobroszyce",
  "Dobrzykowice",
  "Domaszczyn",
  "Duszniki-Zdrój",
  "Dzierżoniów",
  "Długołęka",
  "Gaworzyce",
  "Gryfów Śląski",
  "Góra",
  "Głogów",
  "Głuszyca",
  "Jawor",
  "Jaworzyna Śląska",
  "Jedlina-Zdrój",
  "Jelcz-Laskowice",
  "Jelenia Góra",
  "Jeżów Sudecki",
  "Kamieniec Wrocławski",
  "Kamieniec Ząbkowicki",
  "Kamienna Góra",
  "Karpacz",
  "Kiełczów",
  "Kobierzyce",
  "Kowary",
  "Kudowa-Zdrój",
  "Kąty Wrocławskie",
  "Kłodzko",
  "Legnica",
  "Leśna",
  "Lubawka",
  "Lubań",
  "Lubin",
  "Lubomierz",
  "Lwówek Śląski",
  "Lądek-Zdrój",
  "Milicz",
  "Mirków",
  "Mirsk",
  "Międzybórz",
  "Mysłakowice",
  "Niemcza",
  "Nowa Ruda",
  "Nowogrodziec",
  "Oborniki Śląskie",
  "Oleśnica",
  "Olszyna",
  "Oława",
  "Piechowice",
  "Pieszyce",
  "Pieńsk",
  "Piława Górna",
  "Polanica-Zdrój",
  "Polkowice",
  "Prochowice",
  "Prusice",
  "Przemków",
  "Radwanice",
  "Ruszowice",
  "Siechnice",
  "Smolec",
  "Sobótka",
  "Stronie Śląskie",
  "Strzegom",
  "Strzelin",
  "Syców",
  "Szczawno-Zdrój",
  "Szczytna",
  "Szklarska Poręba",
  "Trzebnica",
  "Twardogóra",
  "Wałbrzych",
  "Wiązów",
  "Wołów",
  "Wrocław",
  "Wysoka",
  "Wąsosz",
  "Zgorzelec",
  "Ziębice",
  "Ząbkowice Śląskie",
  "Złotoryja",
  "Łagiewniki",
  "Ścinawa",
  "Środa Śląska",
  "Świdnica",
  "Świebodzice",
  "Świeradów-Zdrój",
  "Żarów",
  "Żmigród",
  "Aleksandrów Kujawski",
  "Barcin",
  "Białe Błota",
  "Brodnica",
  "Brześć Kujawski",
  "Brzoza",
  "Brzozówka",
  "Bydgoszcz",
  "Cekcyn",
  "Chełmno",
  "Chełmża",
  "Choceń",
  "Chodecz",
  "Ciechocinek",
  "Czernikowo",
  "Dobrcz",
  "Dobre",
  "Dobrzyń nad Wisłą",
  "Dolna Grupa",
  "Drzycim",
  "Dąbrowa Biskupia",
  "Dąbrowa Chełmińska",
  "Gniewkowo",
  "Golub-Dobrzyń",
  "Grudziądz",
  "Grębocin",
  "Górzno",
  "Głogowo",
  "Inowrocław",
  "Izbica Kujawska",
  "Jabłonowo Pomorskie",
  "Janikowo",
  "Janowiec Wielkopolski",
  "Kamień Krajeński",
  "Kcynia",
  "Kikół",
  "Koronowo",
  "Kowal",
  "Kowalewo Pomorskie",
  "Krobia",
  "Kruszwica",
  "Lipno",
  "Lisewo",
  "Lniano",
  "Lubanie",
  "Lubicz Dolny",
  "Lubicz Górny",
  "Lubień Kujawski",
  "Lubraniec",
  "Mała Nieszawka",
  "Mogilno",
  "Mrocza",
  "Nakło nad Notecią",
  "Niemcz",
  "Nowa Wieś Wielka",
  "Nowe",
  "Obrowo",
  "Osie",
  "Osiek Nad Wisłą",
  "Osielsko",
  "Osięciny",
  "Pakość",
  "Piotrków Kujawski",
  "Pruszcz",
  "Raciążek",
  "Radziejów",
  "Radzyń Chełmiński",
  "Rogowo",
  "Rozgarty",
  "Rypin",
  "Sadki",
  "Skępe",
  "Solec Kujawski",
  "Strzelno",
  "Szpetal Górny",
  "Szubin",
  "Sępólno Krajeńskie",
  "Tarkowo Dolne",
  "Topólka",
  "Toruń",
  "Tuchola",
  "Tłuchowo",
  "Unisław",
  "Warlubie",
  "Więcbork",
  "Wąbrzeźno",
  "Włocławek",
  "Zakrzewo",
  "Zamość",
  "Zielonka",
  "Złotniki Kujawskie",
  "Łabiszyn",
  "Łasin",
  "Łochowo",
  "Łubianka",
  "Łysomice",
  "Łążynek",
  "Śliwice",
  "Świecie",
  "Żnin",
  "Adamów",
  "Annopol",
  "Baranów",
  "Bełżec",
  "Bełżyce",
  "Biała Podlaska",
  "Biłgoraj",
  "Borki",
  "Bychawa",
  "Chełm",
  "Chodel",
  "Chomęciska Małe",
  "Ciecierzyn",
  "Cyców",
  "Czemierniki",
  "Drelów",
  "Dęblin",
  "Dębowa Kłoda",
  "Fajsławice",
  "Firlej",
  "Frampol",
  "Garbów I",
  "Glinne",
  "Grabów Szlachecki",
  "Góra Puławska",
  "Hrubieszów",
  "Janów Lubelski",
  "Janów Podlaski",
  "Jastków",
  "Józefów",
  "Kamionka",
  "Karczmiska Pierwsze",
  "Kazimierz Dolny",
  "Kock",
  "Komarówka Podlaska",
  "Konopnica",
  "Konstantynów",
  "Końskowola",
  "Krasnobród",
  "Krasnystaw",
  "Kraśnik",
  "Krzywda",
  "Kurów",
  "Kłoczew",
  "Lubartów",
  "Lublin",
  "Markuszów",
  "Michów",
  "Milejów",
  "Milejów-Osada",
  "Międzyrzec Podlaski",
  "Modliborzyce",
  "Motycz",
  "Nałęczów",
  "Niedrzwica Duża",
  "Niedrzwica Kościelna",
  "Niemce",
  "Opole Lubelskie",
  "Ostrów Lubelski",
  "Parczew",
  "Piaski",
  "Piotrowice",
  "Poniatowa",
  "Puławy",
  "Płoskie",
  "Radawiec Duży",
  "Radzyń Podlaski",
  "Ratoszyn Pierwszy",
  "Rejowiec",
  "Rejowiec Fabryczny",
  "Ryki",
  "Serokomla",
  "Sitaniec",
  "Stoczek Łukowski",
  "Stężyca",
  "Szczebrzeszyn",
  "Tarnogród",
  "Terespol",
  "Tomaszów Lubelski",
  "Trawniki",
  "Turka",
  "Turobin",
  "Urszulin",
  "Urzędów",
  "Werbkowice",
  "Wisznice",
  "Wohyń",
  "Wojcieszków",
  "Wąwolnica",
  "Włodawa",
  "Zamość",
  "Zwierzyniec",
  "Ćmiłów",
  "Łabunie",
  "Łaszczów",
  "Łopiennik Górny",
  "Łuków",
  "Łęczna",
  "Świdnik",
  "Żółkiewka",
  "Babimost",
  "Baczyna",
  "Bobrowniki",
  "Bogdaniec",
  "Borów Wielki",
  "Brzozowiec",
  "Bytom Odrzański",
  "Chwalęcice",
  "Cybinka",
  "Czerwieńsk",
  "Deszczno",
  "Dobiegniew",
  "Drezdenko",
  "Droszków",
  "Drzonków",
  "Dąbrówka Wielkopolska",
  "Gorzów Wielkopolski",
  "Gozdnica",
  "Grabik",
  "Gubin",
  "Górzyca",
  "Iłowa",
  "Janczewo",
  "Jasień",
  "Jenin",
  "Kargowa",
  "Konin Żagański",
  "Konotop",
  "Kostrzyn nad Odrą",
  "Kożuchów",
  "Krosno Odrzańskie",
  "Krzeszyce",
  "Kunowice",
  "Kłodawa",
  "Lipinki Łużyckie",
  "Lubiszyn",
  "Lubniewice",
  "Lubrza",
  "Lubsko",
  "Marzenin",
  "Maszewo",
  "Małomice",
  "Mirocin Górny",
  "Międzyrzecz",
  "Modrzyca",
  "Murzynowo",
  "Niegosławice",
  "Nowa Sól",
  "Nowe Kramsko",
  "Nowe Miasteczko",
  "Nowiny Wielkie",
  "Nowogród Bobrzański",
  "Nowy Kisielin",
  "Ochla",
  "Otyń",
  "Ośno Lubuskie",
  "Przylep",
  "Przytoczna",
  "Pszczew",
  "Pyrzany",
  "Płoty",
  "Racula",
  "Rzepin",
  "Siedlisko",
  "Skwierzyna",
  "Skąpe",
  "Solniki",
  "Stare Kurowo",
  "Stary Kisielin",
  "Strzelce Krajeńskie",
  "Sulechów",
  "Sulęcin",
  "Szczaniec",
  "Szlichtyngowa",
  "Szprotawa",
  "Sława",
  "Słońsk",
  "Słubice",
  "Torzym",
  "Trzciel",
  "Trzebiel",
  "Tuplice",
  "Wawrów",
  "Witnica",
  "Wschowa",
  "Wędrzyn",
  "Zatonie",
  "Zbąszynek",
  "Zielona Góra",
  "Zwierzyn",
  "Łagów",
  "Łęknica",
  "Łężyca",
  "Świdnica",
  "Świebodzin",
  "Żagań",
  "Żary",
  "Aleksandrów Łódzki",
  "Andrespol",
  "Bełchatów",
  "Bełchów",
  "Biała Rawska",
  "Bolesławiec",
  "Brzeziny",
  "Buczek",
  "Bukowiec",
  "Burzenin",
  "Będków",
  "Błaszki",
  "Czestków B",
  "Dobroń",
  "Dobryszyce",
  "Drzewica",
  "Działoszyn",
  "Dłutów",
  "Galewice",
  "Gałków Mały",
  "Glinnik",
  "Gomunice",
  "Gorzkowice",
  "Grabów",
  "Głowno",
  "Jastrzębia",
  "Jeżów",
  "Justynów",
  "Kamieńsk",
  "Kleszczów",
  "Kluki",
  "Kolonia Grabostów",
  "Koluszki",
  "Konstantynów Łódzki",
  "Krośniewice",
  "Ksawerów",
  "Kutno",
  "Lipce Reymontowskie",
  "Lubochnia",
  "Lutomiersk",
  "Lututów",
  "Mokrsko",
  "Moszczenica",
  "Opoczno",
  "Osiedle Niewiadów",
  "Osjaków",
  "Ozorków",
  "Pabianice",
  "Pajęczno",
  "Piotrków Trybunalski",
  "Piątek",
  "Poddębice",
  "Przedbórz",
  "Radomsko",
  "Rawa Mazowiecka",
  "Rogów",
  "Rokiciny-Kolonia",
  "Rozprza",
  "Rusiec",
  "Rzgów",
  "Rząśnia",
  "Rąbień",
  "Sieradz",
  "Skierniewice",
  "Sokolniki",
  "Starowa Góra",
  "Stryków",
  "Strzelce Wielkie",
  "Sulejów",
  "Sulmierzyce",
  "Szadek",
  "Szczerców",
  "Sędziejowice",
  "Tomaszów Mazowiecki",
  "Trębaczew",
  "Tuszyn",
  "Ujazd",
  "Uniejów",
  "Warta",
  "Wartkowice",
  "Widawa",
  "Wieluń",
  "Wieruszów",
  "Wiśniowa Góra",
  "Wola Krzysztoporska",
  "Wolbórz",
  "Wójcin",
  "Włodzimierzów",
  "Zduńska Wola",
  "Zelów",
  "Zgierz",
  "Złoczew",
  "Łask",
  "Łowicz",
  "Łyszkowice",
  "Łódź",
  "Łęczyca",
  "Żarnów",
  "Żychlin",
  "Alwernia",
  "Andrychów",
  "Babice",
  "Biały Dunajec",
  "Biecz",
  "Bobowa",
  "Bochnia",
  "Bolesław",
  "Brzesko",
  "Brzeszcze",
  "Brzezna",
  "Bukowno",
  "Bulowice",
  "Chełmek",
  "Chełmiec",
  "Chocznia",
  "Chrzanów",
  "Ciężkowice",
  "Czchów",
  "Czernichów",
  "Dobczyce",
  "Dobra",
  "Dąbrowa Tarnowska",
  "Gdów",
  "Gorlice",
  "Gorzów",
  "Grybów",
  "Jabłonka",
  "Jadowniki",
  "Jawiszowice",
  "Jordanów",
  "Kalwaria Zebrzydowska",
  "Klucze",
  "Kocmyrzów",
  "Kraków",
  "Krynica-Zdrój",
  "Krzeszowice",
  "Kęty",
  "Kłaj",
  "Libiąż",
  "Limanowa",
  "Lipnica Wielka",
  "Liszki",
  "Maków Podhalański",
  "Michałowice",
  "Miechów",
  "Mogilany",
  "Mszana Dolna",
  "Muszyna",
  "Myślenice",
  "Niedźwiedź",
  "Niepołomice",
  "Nowa Wieś",
  "Nowy Sącz",
  "Nowy Targ",
  "Nowy Wiśnicz",
  "Olkusz",
  "Osiek",
  "Oświęcim",
  "Piwniczna-Zdrój",
  "Podegrodzie",
  "Poronin",
  "Proszowice",
  "Przeciszów",
  "Rabka-Zdrój",
  "Ropa",
  "Siepraw",
  "Skawina",
  "Skała",
  "Skomielna Biała",
  "Spytkowice",
  "Stary Sącz",
  "Sucha Beskidzka",
  "Sułkowice",
  "Szarów",
  "Szczawnica",
  "Szczucin",
  "Słomniki",
  "Tarnów",
  "Trzebinia",
  "Tuchów",
  "Tymbark",
  "Wadowice",
  "Wieliczka",
  "Wojnicz",
  "Wola Filipowska",
  "Wola Rzędzińska",
  "Wolbrom",
  "Zabierzów",
  "Zakliczyn",
  "Zakopane",
  "Zator",
  "Zawoja",
  "Zielonki",
  "Łapanów",
  "Łużna",
  "Łącko",
  "Świątniki Górne",
  "Żabno",
  "Baboszewo",
  "Białobrzegi",
  "Brwinów",
  "Błonie",
  "Chorzele",
  "Chotomów",
  "Ciechanów",
  "Czosnów",
  "Dębe Wielkie",
  "Długosiodło",
  "Garwolin",
  "Gostynin",
  "Grodzisk Mazowiecki",
  "Grójec",
  "Góra Kalwaria",
  "Gąbin",
  "Halinów",
  "Iłża",
  "Jabłonna",
  "Jedlińsk",
  "Jedlnia-Letnisko",
  "Julianów",
  "Józefosław",
  "Józefów",
  "Karczew",
  "Kałuszyn",
  "Kobyłka",
  "Komorów",
  "Konstancin-Jeziorna",
  "Kotuń",
  "Kozienice",
  "Legionowo",
  "Leszno",
  "Lipsko",
  "Magdalenka",
  "Maków Mazowiecki",
  "Marki",
  "Małkinia Górna",
  "Milanówek",
  "Mińsk Mazowiecki",
  "Mrozy",
  "Mszczonów",
  "Mysiadło",
  "Myszyniec",
  "Mława",
  "Nadarzyn",
  "Nasielsk",
  "Nieporęt",
  "Nowa Iwiczna",
  "Nowy Dwór Mazowiecki",
  "Ostrołęka",
  "Ostrów Mazowiecka",
  "Otwock",
  "Ożarów Mazowiecki",
  "Piaseczno",
  "Piastów",
  "Pilawa",
  "Pionki",
  "Podkowa Leśna",
  "Pomiechówek",
  "Pruszków",
  "Przasnysz",
  "Przysucha",
  "Pułtusk",
  "Płock",
  "Płońsk",
  "Raciąż",
  "Radom",
  "Radzymin",
  "Raszyn",
  "Serock",
  "Siedlce",
  "Sierpc",
  "Skaryszew",
  "Sochaczew",
  "Sokołów Podlaski",
  "Stare Babice",
  "Sulejówek",
  "Szydłowiec",
  "Tarczyn",
  "Teresin",
  "Tłuszcz",
  "Warka",
  "Warszawa",
  "Wieliszew",
  "Wiązowna",
  "Wołomin",
  "Wyszków",
  "Węgrów",
  "Zbuczyn",
  "Zielonka",
  "Zwoleń",
  "Ząbki",
  "Łaskarzew",
  "Łochów",
  "Łomianki",
  "Łosice",
  "Żelechów",
  "Żuromin",
  "Żyrardów",
  "Baborów",
  "Biała",
  "Bodzanów Osiedle III",
  "Bogacica",
  "Brzeg",
  "Byczyna",
  "Chrząstowice",
  "Chrząszczyce",
  "Chróścice",
  "Chróścina",
  "Czarnowąsy",
  "Dalachów",
  "Daniec",
  "Dobrodzień",
  "Dobrzeń Mały",
  "Dobrzeń Wielki",
  "Domecko",
  "Dylaki",
  "Dziergowice",
  "Dąbrowa",
  "Gogolin",
  "Gorzów Śląski",
  "Grabin",
  "Grodków",
  "Grodziec",
  "Głogówek",
  "Głubczyce",
  "Głuchołazy",
  "Izbicko",
  "Jemielnica",
  "Jełowa",
  "Kalinów",
  "Kamiennik",
  "Kamień Śląski",
  "Kielcza",
  "Kietrz",
  "Kluczbork",
  "Kolonowskie",
  "Komprachcice",
  "Korfantów",
  "Krapkowice",
  "Krasiejów",
  "Kuniów",
  "Kąty Opolskie",
  "Kędzierzyn-Koźle",
  "Kępa",
  "Lewin Brzeski",
  "Leśnica",
  "Lubsza",
  "Murów",
  "Namysłów",
  "Niemodlin",
  "Nogowczyce",
  "Nowy Świętów",
  "Nysa",
  "Olesno",
  "Opole",
  "Otmuchów",
  "Ozimek",
  "Paczków",
  "Pawłowiczki",
  "Pludry",
  "Pokój",
  "Polska Cerekiew",
  "Polska Nowa Wieś",
  "Popielów",
  "Praszka",
  "Prudnik",
  "Prószków",
  "Rozwadza",
  "Rudniki",
  "Schodnia",
  "Skarbimierz",
  "Skarbimierz Osiedle",
  "Skoroszyce",
  "Staniszcze Małe",
  "Staniszcze Wielkie",
  "Stare Budkowice",
  "Stare Koźle",
  "Stare Siołkowice",
  "Strzelce Opolskie",
  "Strzeleczki",
  "Tarnów Opolski",
  "Turawa",
  "Tułowice",
  "Ujazd",
  "Walce",
  "Wołczyn",
  "Wójcice",
  "Węgry",
  "Zawada",
  "Zawadzkie",
  "Zdzieszowice",
  "Zębowice",
  "Łambinowice",
  "Łosiów",
  "Łubniany",
  "Łącznik",
  "Żywocice",
  "Żędowice",
  "Albigowa",
  "Baranów Sandomierski",
  "Białobrzegi",
  "Boguchwała",
  "Brzeźnica",
  "Brzostek",
  "Brzozów",
  "Błażowa",
  "Chorzelów",
  "Cieszanów",
  "Cmolas",
  "Czarna",
  "Czudec",
  "Dubiecko",
  "Dukla",
  "Dulcza Wielka",
  "Dynów",
  "Dębica",
  "Frysztak",
  "Gorzyce",
  "Grabiny",
  "Głogów Małopolski",
  "Humniska",
  "Hyżne",
  "Iwonicz-Zdrój",
  "Jarosław",
  "Jasionka",
  "Jasło",
  "Jedlicze",
  "Jeżowe",
  "Jodłowa",
  "Kamień",
  "Kańczuga",
  "Kolbuszowa",
  "Korczyna",
  "Kosina",
  "Kraczkowa",
  "Krasne",
  "Krosno",
  "Lesko",
  "Leżajsk",
  "Lubaczów",
  "Lubzina",
  "Majdan Królewski",
  "Malawa",
  "Markowa",
  "Mielec",
  "Narol",
  "Niedźwiada",
  "Nisko",
  "Nowa Dęba",
  "Nowa Sarzyna",
  "Nowy Żmigród",
  "Oleszyce",
  "Olszanica",
  "Orły",
  "Padew Narodowa",
  "Pilzno",
  "Polańczyk",
  "Pruchnik",
  "Przecław",
  "Przemyśl",
  "Przeworsk",
  "Pustków",
  "Pustków-Osiedle",
  "Pysznica",
  "Racławówka",
  "Radomyśl Wielki",
  "Radymno",
  "Rakszawa",
  "Ropczyce",
  "Rudna Wielka",
  "Rudnik nad Sanem",
  "Rymanów",
  "Rzeszów",
  "Sanok",
  "Sieniawa",
  "Skołyszyn",
  "Sokołów Małopolski",
  "Stalowa Wola",
  "Strzyżów",
  "Szówsko",
  "Sędziszów Małopolski",
  "Tarnobrzeg",
  "Trzebownisko",
  "Tuszyma",
  "Tyczyn",
  "Ustrzyki Dolne",
  "Wadowice Górne",
  "Wielopole Skrzyńskie",
  "Wiśniowa",
  "Wola Dalsza",
  "Zaczernie",
  "Zagórz",
  "Zarzecze",
  "Łańcut",
  "Łukawiec",
  "Świlcza",
  "Żołynia",
  "Augustów",
  "Bakałarzewo",
  "Bargłów Kościelny",
  "Biała Woda",
  "Białostoczek",
  "Białowieża",
  "Białystok",
  "Bielsk Podlaski",
  "Boćki",
  "Brańsk",
  "Choroszcz",
  "Ciechanowiec",
  "Czarna Białostocka",
  "Czeremcha",
  "Czeremcha-Wieś",
  "Czyżew",
  "Dobrzyniewo Duże",
  "Drohiczyn",
  "Dąbrowa Białostocka",
  "Fasty",
  "Filipów",
  "Goniądz",
  "Grabowo",
  "Grabówka",
  "Grajewo",
  "Grodzisk",
  "Gródek",
  "Hajnówka",
  "Hryniewicze",
  "Ignatki",
  "Ignatki-Osiedle",
  "Jasionówka",
  "Jedwabne",
  "Jeleniewo",
  "Jeziorko",
  "Juchnowiec Dolny",
  "Juchnowiec Kościelny",
  "Kleosin",
  "Klepacze",
  "Klukowo",
  "Knyszyn",
  "Kolno",
  "Korycin",
  "Kozińce",
  "Krypno Wielkie",
  "Księżyno",
  "Kulesze Kościelne",
  "Kuźnica",
  "Lipsk",
  "Miastkowo",
  "Michałowo",
  "Mołowiste",
  "Mońki",
  "Narew",
  "Nowe Piekuty",
  "Nowogród",
  "Ogrodniczki",
  "Piątnica Poduchowna",
  "Porosły",
  "Puńsk",
  "Raczki",
  "Rajgród",
  "Rutki-Kossaki",
  "Sawino",
  "Sejny",
  "Sidra",
  "Siemiatycze",
  "Sobolewo",
  "Sochonie",
  "Sokoły",
  "Sokółka",
  "Stawiski",
  "Suchowola",
  "Supraśl",
  "Suraż",
  "Suwałki",
  "Szczuczyn",
  "Szepietowo",
  "Sztabin",
  "Szumowo",
  "Trofimówka",
  "Trzcianne",
  "Turośl",
  "Tykocin",
  "Wasilków",
  "Wizna",
  "Wiżajny",
  "Wysokie Mazowieckie",
  "Wąsosz",
  "Zabłudów",
  "Zajęczniki",
  "Zambrów",
  "Zawady",
  "Zaścianki",
  "Łapy",
  "Łomża",
  "Łyski",
  "Śniadowo",
  "Śródlesie",
  "Banino",
  "Bojano",
  "Bolszewo",
  "Borkowo",
  "Brusy",
  "Bytów",
  "Choczewo",
  "Chojnice",
  "Chwaszczyno",
  "Czarna Woda",
  "Czarne",
  "Czersk",
  "Człuchów",
  "Debrzno",
  "Dzierzgoń",
  "Dębnica Kaszubska",
  "Dębogórze",
  "Gdańsk",
  "Gdynia",
  "Gniew",
  "Gowino",
  "Gościcino",
  "Gwieździn",
  "Hel",
  "Juszkowo",
  "Kaliska",
  "Kamienica Szlachecka",
  "Kartuzy",
  "Kielno",
  "Kiełpino",
  "Kobylnica",
  "Kokoszkowy",
  "Kolbudy",
  "Kosakowo",
  "Kowale",
  "Kościerzyna",
  "Kwidzyn",
  "Kębłowo",
  "Kępice",
  "Linia",
  "Lipusz",
  "Lubichowo",
  "Lubowidz",
  "Luzino",
  "Lębork",
  "Malbork",
  "Miastko",
  "Miechucino",
  "Mosty",
  "Nowa Wieś Lęborska",
  "Nowy Dwór Gdański",
  "Nowy Staw",
  "Orle",
  "Pelplin",
  "Pinczyn",
  "Pogórze",
  "Potęgowo",
  "Prabuty",
  "Pruszcz Gdański",
  "Przodkowo",
  "Pszczółki",
  "Puck",
  "Pępowo",
  "Reda",
  "Rotmanka",
  "Rumia",
  "Ryjewo",
  "Sadlinki",
  "Sierakowice",
  "Skarszewy",
  "Skowarcz",
  "Skórcz",
  "Somonino",
  "Sopot",
  "Stara Kiszewa",
  "Starogard Gdański",
  "Stegna",
  "Straszyn",
  "Strzebielino Osiedle",
  "Stężyca",
  "Suchy Dwór",
  "Sycewice",
  "Szemud",
  "Sztum",
  "Słupsk",
  "Tczew",
  "Trąbki Wielkie",
  "Ustka",
  "Wejherowo",
  "Wejherowo-Nanice",
  "Władysławowo",
  "Zblewo",
  "Łeba",
  "Łubiana",
  "Łąg",
  "Łęgowo",
  "Żelistrzewo",
  "Żukowo",
  "Bielsko-Biała",
  "Bieruń",
  "Blachownia",
  "Borucin",
  "Bytom",
  "Będzin",
  "Chełm Śląski",
  "Chorzów",
  "Chybie",
  "Cieszyn",
  "Czechowice-Dziedzice",
  "Czeladź",
  "Czerwionka-Leszczyny",
  "Czyżowice",
  "Częstochowa",
  "Dąbrowa Górnicza",
  "Gierałtowice",
  "Gliwice",
  "Gostyń",
  "Imielin",
  "Jasienica",
  "Jastrzębie-Zdrój",
  "Jaworze",
  "Jaworzno",
  "Jejkowice",
  "Kalety",
  "Katowice",
  "Knurów",
  "Kobiór",
  "Koniecpol",
  "Kornowac",
  "Koszęcin",
  "Koziegłowy",
  "Kozy",
  "Krzepice",
  "Kuźnia Raciborska",
  "Kłobuck",
  "Lubliniec",
  "Lędziny",
  "Marklowice",
  "Miasteczko Śląskie",
  "Mikołów",
  "Milówka",
  "Myszków",
  "Mysłowice",
  "Ogrodzieniec",
  "Olsztyn",
  "Ornontowice",
  "Orzesze",
  "Paniówki",
  "Parzymiechy",
  "Pawłowice",
  "Piekary Śląskie",
  "Pisarzowice",
  "Poraj",
  "Poręba",
  "Przyszowice",
  "Pszczyna",
  "Pszów",
  "Pyskowice",
  "Racibórz",
  "Radlin",
  "Radzionków",
  "Rogoźnik",
  "Ruda Śląska",
  "Rybnik",
  "Rydułtowy",
  "Siemianowice Śląskie",
  "Siewierz",
  "Skoczów",
  "Sosnowiec",
  "Strumień",
  "Suszec",
  "Szczekociny",
  "Szczyrk",
  "Sławków",
  "Tarnowskie Góry",
  "Toszek",
  "Tychy",
  "Ustroń",
  "Wilkowice",
  "Wisła",
  "Wodzisław Śląski",
  "Wojkowice",
  "Wola",
  "Woźniki",
  "Wyry",
  "Węgierska Górka",
  "Zabrze",
  "Zawiercie",
  "Zebrzydowice",
  "Łaziska Górne",
  "Łazy",
  "Łodygowice",
  "Świerklaniec",
  "Świerklany",
  "Świętochłowice",
  "Żarki",
  "Żory",
  "Żywiec",
  "Baćkowice",
  "Bałtów",
  "Bieliny",
  "Bilcza",
  "Bliżyn",
  "Bodzechów",
  "Bodzentyn",
  "Bogoria",
  "Brody",
  "Brzeziny",
  "Busko-Zdrój",
  "Cedzyna",
  "Chmielnik",
  "Chęciny",
  "Daleszyce",
  "Dwikozy",
  "Działoszyce",
  "Fałków",
  "Gnojno",
  "Gowarczów",
  "Górno",
  "Iwaniska",
  "Janik",
  "Jędrzejów",
  "Kazimierza Wielka",
  "Kielce",
  "Kije",
  "Klimontów",
  "Koprzywnica",
  "Kostomłoty Pierwsze",
  "Końskie",
  "Krajno-Parcele",
  "Krasocin",
  "Kuczów",
  "Kunów",
  "Lechów",
  "Leszczyny",
  "Masłów Pierwszy",
  "Małogoszcz",
  "Miedziana Góra",
  "Mirzec",
  "Mniów",
  "Morawica",
  "Nowa Słupia",
  "Nowiny",
  "Nowy Korczyn",
  "Oleśnica",
  "Opatów",
  "Osiek",
  "Ostrowiec Świętokrzyski",
  "Ożarów",
  "Pacanów",
  "Parszów",
  "Pawłów",
  "Piekoszów",
  "Pierzchnica",
  "Piotrkowice",
  "Pińczów",
  "Połaniec",
  "Radlin",
  "Radoszyce",
  "Raków",
  "Rytwiany",
  "Sadowie",
  "Sandomierz",
  "Secemin",
  "Skalbmierz",
  "Skarżysko Kościelne",
  "Skarżysko-Kamienna",
  "Sobków",
  "Solec-Zdrój",
  "Starachowice",
  "Staszów",
  "Stopnica",
  "Strawczyn",
  "Stąporków",
  "Suchedniów",
  "Suków",
  "Szewna",
  "Szydłów",
  "Sędziszów",
  "Tumlin-Podgród",
  "Waśniów",
  "Wiślica",
  "Wodzisław",
  "Wola Jachowa",
  "Wola Morawicka",
  "Wąchock",
  "Włoszczowa",
  "Zagnańsk",
  "Zawichost",
  "Zgórsko",
  "Zrecze Małe",
  "Ćmielów",
  "Łagów",
  "Łoniów",
  "Łopuszno",
  "Łączna",
  "Łążek",
  "Święta Katarzyna",
  "Banie Mazurskie",
  "Barczewo",
  "Bartoszyce",
  "Bartąg",
  "Biała Piska",
  "Biskupiec",
  "Bisztynek",
  "Braniewo",
  "Bratian",
  "Brzozie Lubawskie",
  "Dobre Miasto",
  "Dorotowo",
  "Dywity",
  "Działdowo",
  "Dźwierzuty",
  "Elbląg",
  "Ełk",
  "Frombork",
  "Giedajty",
  "Giżycko",
  "Gołdap",
  "Grodziczno",
  "Grzybowo",
  "Górowo Iławeckie",
  "Iława",
  "Iłowo-Osada",
  "Jamielnik",
  "Janki",
  "Jedwabno",
  "Jeziorany",
  "Jonkowo",
  "Karaś",
  "Kisielice",
  "Korsze",
  "Kowale Oleckie",
  "Kruklanki",
  "Kurzętnik",
  "Kurzętnik Dolny",
  "Kętrzyn",
  "Lidzbark",
  "Lidzbark Warmiński",
  "Lubawa",
  "Lubomino",
  "Marcinkowo",
  "Małdyty",
  "Mikołajki",
  "Miłakowo",
  "Miłki",
  "Miłomłyn",
  "Morąg",
  "Mroczno",
  "Mrągowo",
  "Myszki",
  "Młynary",
  "Narzym",
  "Nidzica",
  "Nowa Wieś Ełcka",
  "Nowe Miasto Lubawskie",
  "Olecko",
  "Olsztyn",
  "Olsztynek",
  "Orneta",
  "Orzysz",
  "Osieka",
  "Ostróda",
  "Pasym",
  "Pasłęk",
  "Piecki",
  "Pieniężno",
  "Pisz",
  "Pozezdrze",
  "Prostki",
  "Płośnica",
  "Radysy",
  "Reszel",
  "Rozogi",
  "Ruciane-Nida",
  "Rudzienice",
  "Rybno",
  "Ryn",
  "Różnowo",
  "Samborowo",
  "Spychowo",
  "Srokowo",
  "Stawiguda",
  "Stradomno",
  "Susz",
  "Szczytno",
  "Sępopol",
  "Tolkmicko",
  "Wawrowice",
  "Wielbark",
  "Wilkasy",
  "Wydminy",
  "Wójtowo",
  "Węgorzewo",
  "Zalewo",
  "Ługwałd",
  "Świętajno",
  "Baranowo",
  "Borek Wielkopolski",
  "Budzyń",
  "Buk",
  "Chodzież",
  "Czapury",
  "Czarnków",
  "Czempiń",
  "Czerwonak",
  "Dopiewo",
  "Dąbrówka",
  "Gniezno",
  "Gostyń",
  "Gołańcz",
  "Grabów nad Prosną",
  "Grodzisk Wielkopolski",
  "Janikowo",
  "Jarocin",
  "Jastrowie",
  "Kalisz",
  "Kamionki",
  "Kiekrz",
  "Kobylin",
  "Komorniki",
  "Konin",
  "Kostrzyn",
  "Kotlin",
  "Koziegłowy",
  "Koło",
  "Kościan",
  "Koźmin Wielkopolski",
  "Krobia",
  "Krotoszyn",
  "Krzywiń",
  "Krzyż Wielkopolski",
  "Kórnik",
  "Kępno",
  "Kłodawa",
  "Leszno",
  "Luboń",
  "Margonin",
  "Miejska Górka",
  "Międzychód",
  "Mosina",
  "Murowana Goślina",
  "Nowe Skalmierzyce",
  "Nowy Tomyśl",
  "Oborniki",
  "Odolanów",
  "Opalenica",
  "Opatówek",
  "Ostrzeszów",
  "Ostrów Wielkopolski",
  "Piaski",
  "Piła",
  "Pleszew",
  "Plewiska",
  "Pniewy",
  "Pobiedziska",
  "Poznań",
  "Przeźmierowo",
  "Puszczykowo",
  "Pyzdry",
  "Rakoniewice",
  "Rawicz",
  "Rogoźno",
  "Rokietnica",
  "Rychtal",
  "Rydzyna",
  "Sieraków",
  "Skoki",
  "Skórzewo",
  "Strzałkowo",
  "Stęszew",
  "Suchy Las",
  "Swarzędz",
  "Szamocin",
  "Szamotuły",
  "Słupca",
  "Tarnowo Podgórne",
  "Trzcianka",
  "Trzemeszno",
  "Turek",
  "Wieleń",
  "Wiry",
  "Witkowo",
  "Wolsztyn",
  "Wronki",
  "Września",
  "Wyrzysk",
  "Wągrowiec",
  "Włoszakowice",
  "Zagórów",
  "Zalasewo",
  "Zbąszyń",
  "Zduny",
  "Złotów",
  "Śmigiel",
  "Śrem",
  "Środa Wielkopolska",
  "Banie",
  "Barlinek",
  "Barwice",
  "Bezrzecze",
  "Białogard",
  "Biały Bór",
  "Bobolice",
  "Borne Sulinowo",
  "Cedynia",
  "Chociwel",
  "Chojna",
  "Choszczno",
  "Czaplinek",
  "Człopa",
  "Darłowo",
  "Dobra",
  "Dobrzany",
  "Dolice",
  "Dołuje",
  "Drawno",
  "Drawsko Pomorskie",
  "Dziwnów",
  "Dębno",
  "Golczewo",
  "Goleniów",
  "Gościno",
  "Gryfice",
  "Gryfino",
  "Grzędzice",
  "Ińsko",
  "Kalisz Pomorski",
  "Kamień Pomorski",
  "Karlino",
  "Kliniska Wielkie",
  "Kobylanka",
  "Konikowo",
  "Koszalin",
  "Kołbaskowo",
  "Kołobrzeg",
  "Lipiany",
  "Maszewo",
  "Mielno",
  "Mierzyn",
  "Mieszkowice",
  "Mirosławiec",
  "Międzyzdroje",
  "Moryń",
  "Morzyczyn",
  "Motaniec",
  "Mrzeżyno",
  "Myślibórz",
  "Mścice",
  "Niechorze",
  "Nowogard",
  "Pełczyce",
  "Pilchowo",
  "Pobierowo",
  "Polanów",
  "Police",
  "Połczyn-Zdrój",
  "Przecław",
  "Pyrzyce",
  "Płoty",
  "Recz",
  "Resko",
  "Rewal",
  "Rosnowo",
  "Rymań",
  "Sarbinowo",
  "Sianów",
  "Stare Bielice",
  "Stargard",
  "Stepnica",
  "Suchań",
  "Sulikowo",
  "Szczecin",
  "Szczecinek",
  "Sławno",
  "Sławoborze",
  "Tanowo",
  "Trzcińsko-Zdrój",
  "Trzebiatów",
  "Tuczno",
  "Tychowo",
  "Ustronie Morskie",
  "Warzymice",
  "Wałcz",
  "Wierzchowo",
  "Wolin",
  "Wołczkowo",
  "Wysiedle",
  "Węgorzyno",
  "Załom",
  "Zieleniewo",
  "Złocieniec",
  "Łobez",
  "Świdwin",
  "Świnoujście",
  "Żelechowo",
];
